### ISSUE TITLE
Stuttering while turning

### ISSUE THREAD

**Issue by kwadroke** [Lewisk3/MechDoomer#5]
I'm seeing stutter and stuttering sounds when turning. 
Is there a particular version of GZDoom that's best for MechDoomer? 

Currently running GZDoom 4.4.2 on Linux

**Comment by Lewisk3** [comment]
I've managed to reproduce a similar sounding issue under Ubuntu 18.04 (Kubuntu). 
I managed to fix the problem by going into Sound Options -> Advanced options -> Sample rate; Set this to anything other than Default then press `Restart sound`

Otherwise, I'm not quite sure what could be causing that, most likely an issue with GZDoom itself.
I also recommend updating to GZDoom 4.5.0.

**Comment by kwadroke** [comment]
Thanks will test and upgrade.

**Comment by kwadroke** [comment]
Upgraded to 4.5.0. Still seeing visual stutter on the Cockpit. HUD is still working fine.

**Comment by kwadroke** [comment]
It seems like the cockpit is being left behind for a split second, then catches up.

**Comment by Lewisk3** [comment]
Sounds like an interpolation issue with GZDoom itself. 
I've tested with the framerate capped to 35fps and still can't reproduce the issue though.
I'm not sure what could be causing this, seeming that I cannot reproduce it for myself.

It could potentially be related to bad/inconsistent frametimes. 
You can do `vid_fps 1` in the console to tell GZDoom to display your current framerate, if it's all over the place then that could be the cause.

**Comment by kwadroke** [comment]
It's all over the place, so apparently it's my machine.

**Comment by kwadroke** [comment]
Will test on my main gaming rig with better specs once I get GZDoom compiled for Fedora.
